Repository ditrit/leto-modelizer-plugin-core, pull requests merged in 2023-08, with the labels that each got.

#200 Feature: Automatic diagram layout
  changelog.md
  cypress/e2e/automatic-layout.feature
  cypress/e2e/drag-and-drop.feature
  cypress/support/step_definitions/html.js
  demo/src/App.vue
  guides/migrations/0.18.0_to_0.X.0.md
  package-lock.json
  package.json
  src/draw/DefaultDrawer.js
  src/draw/DefaultLayout.js
  src/draw/ElkLayout.js
  src/models/DefaultPlugin.js
  tests/unit/draw/DefaultDrawer.spec.js
  tests/unit/draw/DefaultLayout.spec.js
  tests/unit/draw/ElkLayout.spec.js
  tests/unit/models/DefaultPlugin.spec.js
Labels: Technical task

#207 Update migration guide
  guides/migrations/0.18.0_to_0.X.0.md
Labels: documentation

#204 Bugfix: retrieve nested link
  changelog.md
  cypress/e2e/link-creation.feature
  demo/package-lock.json
  demo/src/DemoMetadata.js
  demo/src/DemoParser.js
  package-lock.json
  package.json
  src/draw/DefaultDrawer.js
  src/models/Component.js
  src/models/DefaultData.js
  tests/unit/models/Component.spec.js
  tests/unit/models/DefaultData.spec.js
Labels: Bug

#217 Improvement: Multiple changes to DefaultLayout/ElkLayout/multiple elk changes
  .eslintignore
  .eslintrc.js
  changelog.md
  cypress/e2e/automatic-layout.feature
  cypress/e2e/container-resizing.feature
  cypress/e2e/rename-component-id.feature
  demo/package-lock.json
  demo/src/App.vue
  demo/src/DemoMetadata.js
  demo/src/DemoParser.js
  demo/src/DemoPlugin.js
  demo/src/main.js
  demo/vue.config.js
  guides/migrations/0.18.0_to_0.19.0.md
  guides/migrations/0.19.0_to_0.X.0.md
  package-lock.json
  package.json
  src/draw/DefaultDrawer.js
  src/draw/DefaultLayout.js
  src/draw/ElkLayout.js
  src/models/DefaultConfiguration.js
  src/models/DefaultPlugin.js
  tests/unit/draw/DefaultDrawer.spec.js
  tests/unit/draw/ElkLayout.spec.js
  tests/unit/models/DefaultConfiguration.spec.js
  tests/unit/models/DefaultPlugin.spec.js
Labels: enhancement

#206 Feature: Reposition a component
  changelog.md
  cypress/e2e/automatic-layout.feature
  demo/src/App.vue
  src/draw/DefaultDrawer.js
  src/draw/DefaultLayout.js
  src/draw/ElkLayout.js
  src/models/DefaultConfiguration.js
  src/models/DefaultPlugin.js
  tests/unit/draw/DefaultDrawer.spec.js
  tests/unit/draw/ElkLayout.spec.js
  tests/unit/models/DefaultConfiguration.spec.js
  tests/unit/models/DefaultPlugin.spec.js
Labels: enhancement
